In [82]:
import pandas as pd

In [125]:
#getting the data to be treated
pd.options.display.max_rows = 999
dfs = pd.read_csv('C:/data-hibs/data/FIFA_countries_db.csv')
dfs.head(5)

      0            1     2          3     4         5
0  Code      Country  Code    Country  Code   Country
1   AFG  Afghanistan   GEO    Georgia   OMA      Oman
2   AIA     Anguilla   GER    Germany   PAK  Pakistan
3   ALB      Albania   GHA      Ghana   PAN    Panama
4   ALG      Algeria   GIB  Gibraltar   PAR  Paraguay

In [93]:
#getting rid of the first row of the dataframe
dfs.drop(0)

#setting a new dataframe to work proper
df = pd.DataFrame({'Acronym' : dfs['0'], 
                   'Name' : dfs['1'],
                   'Acronym1': dfs['2'], 
                   'Name1': dfs['3'],
                  'Acronym2': dfs['4'],
                  'Name2': dfs['5']})

#wiping the first row (old column titles)
df.drop(0)
df.head(5)

  Acronym         Name Acronym1      Name1 Acronym2     Name2
0    Code      Country     Code    Country     Code   Country
1     AFG  Afghanistan      GEO    Georgia      OMA      Oman
2     AIA     Anguilla      GER    Germany      PAK  Pakistan
3     ALB      Albania      GHA      Ghana      PAN    Panama
4     ALG      Algeria      GIB  Gibraltar      PAR  Paraguay

In [85]:
#creating a acronyms only dataframe
acronym = pd.DataFrame(df['Acronym'])
acronym1 = pd.DataFrame(df['Acronym1'])
acronym2 = pd.DataFrame(df['Acronym2'])

#cleaning unnecessary rows, rows_to_drop2
rows_to_drop = [0, 72]
rows_to_drop2 = [0,70,71,72]
acronym = acronym.drop(rows_to_drop)
acronym1 = acronym1.drop(rows_to_drop)
acronym2 = acronym2.drop(rows_to_drop2)

#setting all dataframes with the same column name, making the pd.concat work properly
acronym.columns = ['Acronym']
acronym1.columns = ['Acronym']
acronym2. columns = ['Acronym']

In [86]:
#all acronyms are inserted in the same dataframe
combined_df = pd.concat([acronym, acronym1, acronym2], axis=0, ignore_index=True)
acronymdf = combined_df

In [141]:
#creating countries name dataframes for further concat

df_name = pd.DataFrame(dfs['1'])
df_name2 = pd.DataFrame(dfs['3'])
df_name3 = pd.DataFrame(dfs['5'])

#unnecessary rows cleaned
rows_to_drop = [0,72]
rows_to_drop2 = [0,70,71,72]
df_name = df_name.drop(rows_to_drop)
df_name2 = df_name2.drop(rows_to_drop)
df_name3 = df_name3.drop(rows_to_drop2)

#all the columns put on the same name to map the pd.concat properly
df_name.columns = ['Name']
df_name2.columns = ['Name']
df_name3. columns = ['Name']

#all countries names are now put in the same dataframe
data = pd.concat([df_name, df_name2, df_name3], axis=0, ignore_index=True)
data

                                 Name
0                         Afghanistan
1                            Anguilla
2                             Albania
3                             Algeria
4                             Andorra
5                              Angola
6                           Argentina
7                             Armenia
8                               Aruba
9                      American Samoa
10                Antigua and Barbuda
11                          Australia
12                            Austria
13                         Azerbaijan
14                            Bahamas
15                         Bangladesh
16                            Burundi
17                            Belgium
18                              Benin
19                            Bermuda
20                       Burkina Faso
21                            Bahrain
22                             Bhutan
23             Bosnia and Herzegovina
24                            Belarus
25                             Belize
26                            Bolivia
27                           Botswana
28                             Brazil
29                           Barbados
30                             Brunei
31                           Bulgaria
32                           Cambodia
33                             Canada
34                     Cayman Islands
35                              Congo
36                               Chad
37                              Chile
38                           China PR
39                      Côte d'Ivoire
40                           Cameroon
41                           DR Congo
42                       Cook Islands
43                           Colombia
44                            Comoros
45                         Cape Verde
46                         Costa Rica
47                            Croatia
48           Central African Republic
49                               Cuba
50                            Curaçao
51                             Cyprus
52                     Czech Republic
53                            Denmark
54                           Djibouti
55                           Dominica
56                 Dominican Republic
57                            Ecuador
58                              Egypt
59                            England
60                  Equatorial Guinea
61                            Eritrea
62                              Spain
63                            Estonia
64                           Ethiopia
65                               Fiji
66                            Finland
67                             France
68                      Faroe Islands
69                              Gabon
70                             Gambia
71                            Georgia
72                            Germany
73                              Ghana
74                          Gibraltar
75                      Guinea-Bissau
76                             Greece
77                            Grenada
78                          Guatemala
79                             Guinea
80                               Guam
81                             Guyana
82                              Haiti
83                          Hong Kong
84                           Honduras
85                            Hungary
86                          Indonesia
87                              India
88                Republic of Ireland
89                               Iran
90                               Iraq
91                            Iceland
92                             Israel
93                              Italy
94                            Jamaica
95                             Jordan
96                              Japan
97                         Kazakhstan
98                              Kenya
99                         Kyrgyzstan
100                    Korea Republic
101                      Saudi Arabia
102                            Kuwait
103                            Kosovo
104                              Laos
105                           Liberia
106                             Libya
107                       Saint Lucia
108                           Lesotho
109                           Lebanon
110                     Liechtenstein
111                         Lithuania
112                        Luxembourg
113                            Latvia
114                             Macau
115                        Madagascar
116                           Morocco
117                          Malaysia
118                           Moldova
119                          Maldives
120                            Mexico
121                          Mongolia
122                   North Macedonia
123                              Mali
124                             Malta
125                        Montenegro
126                        Mozambique
127                         Mauritius
128                        Montserrat
129                        Mauritania
130                            Malawi
131                           Myanmar
132                           Namibia
133                         Nicaragua
134                     New Caledonia
135                       Netherlands
136                             Nepal
137                           Nigeria
138                             Niger
139                  Northern Ireland
140                            Norway
141                       New Zealand
142                              Oman
143                          Pakistan
144                            Panama
145                          Paraguay
146                              Peru
147                       Philippines
148                         Palestine
149                  Papua New Guinea
150                            Poland
151                          Portugal
152                         Korea DPR
153                       Puerto Rico
154                             Qatar
155                           Romania
156                      South Africa
157                            Russia
158                            Rwanda
159                             Samoa
160                          Scotland
161                           Senegal
162                        Seychelles
163                         Singapore
164             Saint Kitts and Nevis
165                      Sierra Leone
166                       El Salvador
167                        San Marino
168                   Solomon Islands
169                           Somalia
170                            Serbia
171                         Sri Lanka
172                       South Sudan
173             São Tomé and Príncipe
174                             Sudan
175                       Switzerland
176                          Suriname
177                          Slovakia
178                          Slovenia
179                            Sweden
180                          Eswatini
181                             Syria
182                            Tahiti
183                          Tanzania
184          Turks and Caicos Islands
185                             Tonga
186                          Thailand
187                        Tajikistan
188                      Turkmenistan
189                       Timor-Leste
190                              Togo
191                    Chinese Taipei
192               Trinidad and Tobago
193                           Tunisia
194                            Turkey
195              United Arab Emirates
196                            Uganda
197                           Ukraine
198                           Uruguay
199                               USA
200                        Uzbekistan
201                           Vanuatu
202                         Venezuela
203            British Virgin Islands
204                           Vietnam
205  Saint Vincent and the Grenadines
206                 US Virgin Islands
207                             Wales
208                             Yemen
209                            Zambia
210                          Zimbabwe