In [23]:
#importing necessary libraries
import pandas as pd
import html

In [24]:
#reading the .html db exported from Football Manager 2022 print feature
html_db = pd.read_html('C:\data-hibs\data\players.html')
html_db

[         UID                  Name  Nat  Age                  Position  \
 0   29087736            Matt Macey  ENG   26                        GK
 1   61013783        David Mitchell  SCO   31                        GK
 2   96075402      Kevin DÄ
 browski  POL   23                        GK
 3    5207982       Darren McGregor  SCO   35                     D (C)
 4   61003672           Paul Hanlon  SCO   31                     D (C)
 5   61077396         Ryan Porteous  SCO   22                     D (C)
 6   18102074         Rocky Bushiri  BEL   21        D (RC), WB (R), DM
 7   28116307          Harry Clarke  ENG   20            D (RC), WB (R)
 8   61028791           Paul McGinn  SCO   30            D (RC), WB (R)
 9   61066315          Chris Cadden  SCO   24       D/WB (R), M/AM (RC)
 10   5217061       Lewis Stevenson  SCO   33                  D/WB (L)
 11  61093823             Josh Doig  SCO   19                  D/WB (L)
 12  28105523      Jake Doyle-Hayes  IRL   22                 DM, M (C)
 13  36062516           Alex GogiÄ  CYP   27                 DM, M (C)
 14  29083920           Drey Wright  ENG   26  WB (R), M (RL), AM (RLC)
 15  29125333      Demetri Mitchell  ENG   24           WB (L), AM (RL)
 16  28049656            Joe Newell  ENG   28                     M (C)
 17  61015863           Scott Allan  SCO   29                  M/AM (C)
 18  61068991         Kyle Magennis  SCO   22                  M/AM (C)
 19  90086631         Josh Campbell  SCO   21                  M/AM (C)
 20  29179387        Ewan Henderson  SCO   21           M (C), AM (RLC)
 21  53151878           Runar Hauge  NOR   19                 M/AM (RL)
 22  72051143         Chris Mueller  USA   24           M (R), AM (RLC)
 23  61092645        Steven Bradley  SCO   19                   AM (RC)
 24    356951          Jamie Murphy  SCO   31                    AM (L)
 25  28122192      Sylvester Jasper  BUL   19                   AM (RL)
 26  53179963  Elias Hoff Melkersen  NOR   18            AM (R), ST (C)
 27  61078239           James Scott  SCO   20           AM (RL), ST (C)
 28  61070818          Kevin Nisbet  SCO   24                    ST (C)
 29  74030889      Christian Doidge  WAL   28                    ST (C)

     Height Weight 2nd Nat Preferred Foot
 0   205 cm  85 kg     NaN         Either
 1   183 cm  84 kg     NaN     Right Only
 2   197 cm  81 kg     NaN          Right
 3   183 cm  88 kg     NaN          Right
 4   180 cm  70 kg     NaN           Left
 5   188 cm  75 kg     NaN          Right
 6   187 cm  89 kg     COD          Right
 7   188 cm  81 kg     NaN          Right
 8   176 cm  66 kg     NaN          Right
 9   183 cm  67 kg     NaN          Right
 10  171 cm  67 kg     NaN           Left
 11  189 cm  81 kg     NaN           Left
 12  175 cm  73 kg     NaN          Right
 13  185 cm  83 kg     SRB          Right
 14  178 cm  66 kg     NaN          Right
 15  181 cm  66 kg     NaN      Left Only
 16  185 cm  71 kg     NaN           Left
 17  175 cm  70 kg     NaN          Right
 18  181 cm  80 kg     NaN          Right
 19  175 cm  73 kg     NaN          Right
 20  181 cm  70 kg     NaN         Either
 21  175 cm  71 kg     NaN          Right
 22  176 cm  77 kg     NaN          Right
 23  187 cm  78 kg     NaN         Either
 24  176 cm  64 kg     NaN     Right Only
 25  180 cm  65 kg     NGA          Right
 26  178 cm  72 kg     NaN          Right
 27  189 cm  87 kg     NaN          Right
 28  180 cm  77 kg     NaN          Right
 29  186 cm  77 kg     NaN          Right  ]

In [25]:
#turning the list into a proper Pandas Data Frame
db_to_pdDF = pd.concat(html_db)
df = pd.DataFrame(db_to_pdDF)
df

,UID,Name,Nat,Age,Position,Height,Weight,2nd Nat,Preferred Foot
0,29087736,Matt Macey,ENG,26,GK,205 cm,85 kg,NaN,Either
1,61013783,David Mitchell,SCO,31,GK,183 cm,84 kg,NaN,Right Only
2,96075402,Kevin DÄ browski,POL,23,GK,197 cm,81 kg,NaN,Right
3,5207982,Darren McGregor,SCO,35,D (C),183 cm,88 kg,NaN,Right
4,61003672,Paul Hanlon,SCO,31,D (C),180 cm,70 kg,NaN,Left
5,61077396,Ryan Porteous,SCO,22,D (C),188 cm,75 kg,NaN,Right
6,18102074,Rocky Bushiri,BEL,21,"D (RC), WB (R), DM",187 cm,89 kg,COD,Right
7,28116307,Harry Clarke,ENG,20,"D (RC), WB (R)",188 cm,81 kg,NaN,Right
8,61028791,Paul McGinn,SCO,30,"D (RC), WB (R)",176 cm,66 kg,NaN,Right
9,61066315,Chris Cadden,SCO,24,"D/WB (R), M/AM (RC)",183 cm,67 kg,NaN,Right
10,5217061,Lewis Stevenson,SCO,33,D/WB (L),171 cm,67 kg,NaN,Left
11,61093823,Josh Doig,SCO,19,D/WB (L),189 cm,81 kg,NaN,Left
12,28105523,Jake Doyle-Hayes,IRL,22,"DM, M (C)",175 cm,73 kg,NaN,Right
13,36062516,Alex GogiÄ,CYP,27,"DM, M (C)",185 cm,83 kg,SRB,Right
14,29083920,Drey Wright,ENG,26,"WB (R), M (RL), AM (RLC)",178 cm,66 kg,NaN,Right
15,29125333,Demetri Mitchell,ENG,24,"WB (L), AM (RL)",181 cm,66 kg,NaN,Left Only
16,28049656,Joe Newell,ENG,28,M (C),185 cm,71 kg,NaN,Left
17,61015863,Scott Allan,SCO,29,M/AM (C),175 cm,70 kg,NaN,Right
18,61068991,Kyle Magennis,SCO,22,M/AM (C),181 cm,80 kg,NaN,Right
19,90086631,Josh Campbell,SCO,21,M/AM (C),175 cm,73 kg,NaN,Right
20,29179387,Ewan Henderson,SCO,21,"M (C), AM (RLC)",181 cm,70 kg,NaN,Either
21,53151878,Runar Hauge,NOR,19,M/AM (RL),175 cm,71 kg,NaN,Right
22,72051143,Chris Mueller,USA,24,"M (R), AM (RLC)",176 cm,77 kg,NaN,Right
23,61092645,Steven Bradley,SCO,19,AM (RC),187 cm,78 kg,NaN,Either
24,356951,Jamie Murphy,SCO,31,AM (L),176 cm,64 kg,NaN,Right Only
25,28122192,Sylvester Jasper,BUL,19,AM (RL),180 cm,65 kg,NGA,Right
26,53179963,Elias Hoff Melkersen,NOR,18,"AM (R), ST (C)",178 cm,72 kg,NaN,Right
27,61078239,James Scott,SCO,20,"AM (RL), ST (C)",189 cm,87 kg,NaN,Right
28,61070818,Kevin Nisbet,SCO,24,ST (C),180 cm,77 kg,NaN,Right
29,74030889,Christian Doidge,WAL,28,ST (C),186 cm,77 kg,NaN,Right

In [26]:
#treating some wrong data in the 'Name' column
player_UID = 96075402
df.loc[df['UID'] == player_UID, 'Name'] = 'Kevin Dąbrowski'

player_UID2 = 36062516
df.loc[df['UID'] == player_UID2, 'Name'] = 'Alex Gogić'
df.head(5)

,UID,Name,Nat,Age,Position,Height,Weight,2nd Nat,Preferred Foot
0,29087736,Matt Macey,ENG,26,GK,205 cm,85 kg,NaN,Either
1,61013783,David Mitchell,SCO,31,GK,183 cm,84 kg,NaN,Right Only
2,96075402,Kevin Dąbrowski,POL,23,GK,197 cm,81 kg,NaN,Right
3,5207982,Darren McGregor,SCO,35,D (C),183 cm,88 kg,NaN,Right
4,61003672,Paul Hanlon,SCO,31,D (C),180 cm,70 kg,NaN,Left

In [27]:
df.to_csv('../treated data/players.csv')